In [81]:
import pandas as pd
import numpy as np
#df = pd.read_csv('olympics.csv')
#df.head()
df = pd.read_csv('olympics.csv', index_col = 0, skiprows=1)
df.head()

,№ Summer,01 !,02 !,03 !,Total,№ Winter,01 !.1,02 !.1,03 !.1,Total.1,№ Games,01 !.2,02 !.2,03 !.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [82]:
for col in df.columns:
    #print(col[:3])
    if col[:2]=='01':
        df.rename(columns={col:'Gold' + col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver' + col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze' + col[4:]}, inplace=True)
    if col[:3]=='№':
        df.rename(columns={col:'#' + col[3:]}, inplace=True) 

df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total
Afghanistan (AFG),13,0,0,2,2,0,0,0,0,0,13,0,0,2,2
Algeria (ALG),12,5,2,8,15,3,0,0,0,0,15,5,2,8,15
Argentina (ARG),23,18,24,28,70,18,0,0,0,0,41,18,24,28,70
Armenia (ARM),5,1,2,9,12,6,0,0,0,0,11,1,2,9,12
Australasia (ANZ) [ANZ],2,3,4,5,12,0,0,0,0,0,2,3,4,5,12

In [83]:
df['conutry']=df.index
df = df.reset_index(drop=True)
df

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,conutry
0,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
1,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
2,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
3,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
4,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]
5,25,139,152,177,468,18,5,3,4,12,43,144,155,181,480,Australia (AUS) [AUS] [Z]
6,26,18,33,35,86,22,59,78,81,218,48,77,111,116,304,Austria (AUT)
7,5,6,5,15,26,5,0,0,0,0,10,6,5,15,26,Azerbaijan (AZE)
8,15,5,2,5,12,0,0,0,0,0,15,5,2,5,12,Bahamas (BAH)
9,8,0,0,1,1,0,0,0,0,0,8,0,0,1,1,Bahrain (BRN)
10,11,0,0,1,1,0,0,0,0,0,11,0,0,1,1,Barbados (BAR) [BAR]
11,5,12,24,39,75,6,6,4,5,15,11,18,28,44,90,Belarus (BLR)
12,25,37,52,53,142,20,1,1,3,5,45,38,53,56,147,Belgium (BEL)
13,17,0,0,1,1,7,0,0,0,0,24,0,0,1,1,Bermuda (BER)
14,3,0,1,3,4,0,0,0,0,0,3,0,1,3,4,Bohemia (BOH) [BOH] [Z]
15,9,0,1,0,1,0,0,0,0,0,9,0,1,0,1,Botswana (BOT)
16,21,23,30,55,108,7,0,0,0,0,28,23,30,55,108,Brazil (BRA)
17,1,0,0,2,2,0,0,0,0,0,1,0,0,2,2,British West Indies (BWI) [BWI]
18,19,51,85,78,214,19,1,2,3,6,38,52,87,81,220,Bulgaria (BUL) [H]
19,5,1,0,0,1,0,0,0,0,0,5,1,0,0,1,Burundi (BDI)
20,13,3,1,1,5,1,0,0,0,0,14,3,1,1,5,Cameroon (CMR)
21,25,59,99,121,279,22,62,56,52,170,47,121,155,173,449,Canada (CAN)
22,22,2,7,4,13,16,0,0,0,0,38,2,7,4,13,Chile (CHI) [I]
23,9,201,146,126,473,10,12,22,19,53,19,213,168,145,526,China (CHN) [CHN]
24,18,2,6,11,19,1,0,0,0,0,19,2,6,11,19,Colombia (COL)
25,14,1,1,2,4,6,0,0,0,0,20,1,1,2,4,Costa Rica (CRC)
26,12,0,1,0,1,0,0,0,0,0,12,0,1,0,1,Ivory Coast (CIV) [CIV]
27,6,6,7,10,23,7,4,6,1,11,13,10,13,11,34,Croatia (CRO)
28,19,72,67,70,209,0,0,0,0,0,19,72,67,70,209,Cuba (CUB) [Z]
29,9,0,1,0,1,10,0,0,0,0,19,0,1,0,1,Cyprus (CYP)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
117,16,0,2,0,2,0,0,0,0,0,16,0,2,0,2,Sri Lanka (SRI) [SRI]
118,11,0,1,0,1,0,0,0,0,0,11,0,1,0,1,Sudan (SUD)
119,11,1,0,1,2,0,0,0,0,0,11,1,0,1,2,Suriname (SUR) [E]
120,26,143,164,176,483,22,50,40,54,144,48,193,204,230,627,Sweden (SWE) [Z]
121,27,47,73,65,185,22,50,40,48,138,49,97,113,113,323,Switzerland (SUI)
122,12,1,1,1,3,0,0,0,0,0,12,1,1,1,3,Syria (SYR)
123,13,2,7,12,21,11,0,0,0,0,24,2,7,12,21,Chinese Taipei (TPE) [TPE] [TPE2]
124,5,0,1,2,3,4,0,0,0,0,9,0,1,2,3,Tajikistan (TJK)
125,12,0,2,0,2,0,0,0,0,0,12,0,2,0,2,Tanzania (TAN) [TAN]
126,15,7,6,11,24,3,0,0,0,0,18,7,6,11,24,Thailand (THA)
127,9,0,0,1,1,1,0,0,0,0,10,0,0,1,1,Togo (TOG)
128,8,0,1,0,1,1,0,0,0,0,9,0,1,0,1,Tonga (TGA)
129,16,2,5,11,18,3,0,0,0,0,19,2,5,11,18,Trinidad and Tobago (TRI) [TRI]
130,13,3,3,4,10,0,0,0,0,0,13,3,3,4,10,Tunisia (TUN)
131,21,39,25,24,88,16,0,0,0,0,37,39,25,24,88,Turkey (TUR)
132,14,2,3,2,7,0,0,0,0,0,14,2,3,2,7,Uganda (UGA)
133,5,33,27,55,115,6,2,1,4,7,11,35,28,59,122,Ukraine (UKR)
134,8,1,0,0,1,0,0,0,0,0,8,1,0,0,1,United Arab Emirates (UAE)
135,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,United States (USA) [P] [Q] [R] [Z]
136,20,2,2,6,10,1,0,0,0,0,21,2,2,6,10,Uruguay (URU)
137,5,5,5,10,20,6,1,0,0,1,11,6,5,10,21,Uzbekistan (UZB)
138,17,2,2,8,12,4,0,0,0,0,21,2,2,8,12,Venezuela (VEN)
139,14,0,2,0,2,0,0,0,0,0,14,0,2,0,2,Vietnam (VIE)
140,11,0,1,0,1,7,0,0,0,0,18,0,1,0,1,Virgin Islands (ISV)
141,16,26,29,28,83,14,0,3,1,4,30,26,32,29,87,Yugoslavia (YUG) [YUG]
142,1,0,1,2,3,0,0,0,0,0,1,0,1,2,3,Independent Olympic Participants (IOP) [IOP]
143,12,0,1,1,2,0,0,0,0,0,12,0,1,1,2,Zambia (ZAM) [ZAM]
144,12,3,4,1,8,1,0,0,0,0,13,3,4,1,8,Zimbabwe (ZIM) [ZIM]
145,3,8,5,4,17,0,0,0,0,0,3,8,5,4,17,Mixed team (ZZX) [ZZX]
146,27,4809,4775,5130,14714,22,959,958,948,2865,49,5768,5733,6078,17579,Totals

In [84]:
name = []
for ii in df['conutry']:
    a=ii.find('(')
    b=ii.find(')')
    c=ii[a+1:b]
    #print(c)
    name.append(c)
#print(name)
short = pd.DataFrame(name)
short
df['Country_Index'] = short
#df
df = df.set_index('Country_Index')
#df

In [86]:
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,conutry
Country_Index,,,,,,,,,,,,,,,,
AFG,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
ALG,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
ARG,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
ARM,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
ANZ,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]

In [88]:
df.loc['TPE']

# Summer                                         13
Gold                                              2
Silver                                            7
Bronze                                           12
Total                                            21
# Winter                                         11
Gold.1                                            0
Silver.1                                          0
Bronze.1                                          0
Total.1                                           0
# Games                                          24
Gold.2                                            2
Silver.2                                          7
Bronze.2                                         12
Combined total                                   21
conutry           Chinese Taipei (TPE) [TPE] [TPE2]
Name: TPE, dtype: object

In [89]:
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,conutry
Country_Index,,,,,,,,,,,,,,,,
AFG,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,Afghanistan (AFG)
ALG,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,Algeria (ALG)
ARG,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,Argentina (ARG)
ARM,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,Armenia (ARM)
ANZ,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,Australasia (ANZ) [ANZ]

In [90]:
import pandas as pd
df = pd.read_csv('census.csv')
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [101]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [97]:
df_NM = df.where(df['STNAME'] == 'New Mexico')

In [98]:
df_NM = df_NM.dropna()
df_NM.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1826,40.0,4.0,8.0,35.0,0.0,New Mexico,New Mexico,2059179.0,2059192.0,2064741.0,...,0.044413,-3.419154,-5.109690,-6.758128,-6.402799,1.100660,-1.907270,-3.665188,-5.111616,-4.661594
1827,50.0,4.0,8.0,35.0,1.0,New Mexico,Bernalillo County,662564.0,662555.0,664117.0,...,2.083069,-1.738625,-3.467642,-4.541722,-4.649746,3.327812,0.002980,-1.739014,-2.569249,-2.595516
1828,50.0,4.0,8.0,35.0,3.0,New Mexico,Catron County,3725.0,3725.0,3734.0,...,-0.537562,-14.965986,0.000000,-7.878447,-18.025751,-0.537562,-14.965986,0.000000,-7.878447,-18.025751
1829,50.0,4.0,8.0,35.0,5.0,New Mexico,Chaves County,65645.0,65645.0,65746.0,...,-6.376163,-2.890459,-1.396319,-7.160955,-4.999962,-5.584849,-2.327580,-0.698160,-6.281007,-3.996930
1830,50.0,4.0,8.0,35.0,6.0,New Mexico,Cibola County,27213.0,27213.0,27313.0,...,0.802436,-13.199876,-1.935013,-11.071931,-2.673454,1.167180,-12.543529,-1.204819,-10.085323,-1.684642

In [99]:
np.sum(df_NM['CENSUS2010POP'])

4118358.0

In [102]:
df['SUMLEV'].unique()

array([40, 50])

In [103]:
df_NM['SUMLEV'].unique()

array([ 40.,  50.])

In [146]:
purchase_1 = pd.Series({'Name': 'Chris',
                        'Item Purchased': 'Dog Food',
                        'Cost': 22.50})
purchase_2 = pd.Series({'Name': 'Kevyn',
                        'Item Purchased': 'Kitty Litter',
                        'Cost': 2.50})
purchase_3 = pd.Series({'Name': 'Vinod',
                        'Item Purchased': 'Bird Seed',
                        'Cost': 5.00})

df = pd.DataFrame([purchase_1, purchase_2, purchase_3], index=['Store 1', 'Store 1', 'Store 2'])
#df['Location'] = df.index
#df = df.set_index(['Location', 'Name'])
df = df.set_index([df.index, 'Name'])
df.index.names = ['Location', 'Name']
df
df = df.append(pd.Series(data={'Cost': 3.00, 'Item Purchased': 'Kitty Food'}, name=('Store 2', 'Kevyn')))
df

                Cost Item Purchased
Location Name
Store 1  Chris  22.5       Dog Food
         Kevyn   2.5   Kitty Litter
Store 2  Vinod   5.0      Bird Seed
         Kevyn   3.0     Kitty Food

In [171]:
import pandas as pd
df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:3]=='№':
        df.rename(columns={col:'#'+col[3:]}, inplace=True)

#df.tail()
names_ids = df.index.str.split('(') # split the index by '('
#print(names_ids.str[0], names_ids.str[1].str[:3])
#print(names_ids.str[1].str[:3])
df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Afghanistan,13,0,0,2,2,0,0,0,0,0,13,0,0,2,2,AFG
Algeria,12,5,2,8,15,3,0,0,0,0,15,5,2,8,15,ALG
Argentina,23,18,24,28,70,18,0,0,0,0,41,18,24,28,70,ARG
Armenia,5,1,2,9,12,6,0,0,0,0,11,1,2,9,12,ARM
Australasia,2,3,4,5,12,0,0,0,0,0,2,3,4,5,12,ANZ

In [172]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

# Summer           13
Gold                0
Silver              0
Bronze              2
Total               2
# Winter            0
Gold.1              0
Silver.1            0
Bronze.1            0
Total.1             0
# Games            13
Gold.2              0
Silver.2            0
Bronze.2            2
Combined total      2
ID                AFG
Name: Afghanistan , dtype: object

In [205]:
def answer_one():
    #df_copy = df.where(df['Gold']==max(df['Gold']))
    #df_copy = df_copy.dropna()
    #return df_copy.index.tolist()
    return df[df['Gold']==max(df['Gold'])]
answer_one()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [204]:
def answer_two():
    #df_copy=df.where(df['Gold']-df['Gold.1']==max(df['Gold']-df['Gold.1']))
    #df_copy = df_copy.dropna()
    #return df_copy.index.tolist()
    return df[df['Gold']-df['Gold.1']==max(df['Gold']-df['Gold.1'])]
answer_two()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
United States,26,976,757,666,2399,22,96,102,84,282,48,1072,859,750,2681,USA

In [220]:
def answer_three():
    df_copy = df.where((df['Gold']>0) & (df['Gold.1']>0))
    df_copy = df_copy.dropna()
    a= df_copy['Gold']-df_copy['Gold.1']
    b= df_copy['Gold']+df_copy['Gold.1']
    c= max(a/b)
    return df_copy[(df_copy['Gold']-df_copy['Gold.1'])/(df_copy['Gold']+df_copy['Gold.1']) == c]
answer_three()

,# Summer,Gold,Silver,Bronze,Total,# Winter,Gold.1,Silver.1,Bronze.1,Total.1,# Games,Gold.2,Silver.2,Bronze.2,Combined total,ID
Bulgaria,19.0,51.0,85.0,78.0,214.0,19.0,1.0,2.0,3.0,6.0,38.0,52.0,87.0,81.0,220.0,BUL

In [231]:
def answer_four():
    df['Points']=df['Gold.2']*3+df['Silver.2']*2+df['Bronze.2']
    return df['Points']

Afghanistan                             2
Algeria                                27
Argentina                             130
Armenia                                16
Australasia                            22
Australia                             923
Austria                               569
Azerbaijan                             43
Bahamas                                24
Bahrain                                 1
Barbados                                1
Belarus                               154
Belgium                               276
Bermuda                                 1
Bohemia                                 5
Botswana                                2
Brazil                                184
British West Indies                     2
Bulgaria                              411
Burundi                                 3
Cameroon                               12
Canada                                846
Chile                                  24
China                                1120
Colombia                               29
Costa Rica                              7
Ivory Coast                             2
Croatia                                67
Cuba                                  420
Cyprus                                  2
                                     ...
Spain                                 268
Sri Lanka                               4
Sudan                                   2
Suriname                                4
Sweden                               1217
Switzerland                           630
Syria                                   6
Chinese Taipei                         32
Tajikistan                              4
Tanzania                                4
Thailand                               44
Togo                                    1
Tonga                                   2
Trinidad and Tobago                    27
Tunisia                                19
Turkey                                191
Uganda                                 14
Ukraine                               220
United Arab Emirates                    3
United States                        5684
Uruguay                                16
Uzbekistan                             38
Venezuela                              18
Vietnam                                 4
Virgin Islands                          2
Yugoslavia                            171
Independent Olympic Participants        4
Zambia                                  3
Zimbabwe                               18
Mixed team                             38
Name: Points, Length: 146, dtype: int64

In [130]:
import pandas as pd
df = pd.read_csv('census.csv')
df = df[df['SUMLEV'] == 50]
df = df.set_index(['STNAME'])

In [131]:
df_copy = df.drop('District of Columbia')
df_state = df_copy.index.unique()

In [132]:
max = 0
iindex = 0
for i in range(len(df_state)):    
    ctycount = df_copy.loc[df_state[i],'CTYNAME'].count()
    if(ctycount > max):
        max = ctycount
        iindex = i
print(df_state[iindex])

Texas

In [33]:
#df_copy.loc[:,['CTYNAME','CENSUS2010POP']]

In [137]:
import pandas as pd
census_df = pd.read_csv('census.csv')
df_copy = census_df[census_df['SUMLEV'] == 50]
df_copy = df_copy.set_index('STNAME')
df_copy = df_copy.drop('District of Columbia')
df_state = df_copy.index.unique()
df_ser = pd.Series()
for i in range(len(df_state)):  
    df_AL = df_copy.loc[df_state[i],['CTYNAME','CENSUS2010POP']].sort_values(['CENSUS2010POP','CTYNAME'], ascending=[False, False])
    sum = 0
    for j in range(3):
        sum = sum+df_AL.iloc[j][1]
    df_ser = df_ser.append(pd.Series({df_state[i]:sum}))
df_pop = pd.DataFrame(df_ser, columns = ['POP'])
print(df_pop.sort_values('POP',ascending=[False])[:3].index.tolist())

['California', 'Texas', 'Illinois']

In [157]:
import pandas as pd
census_df = pd.read_csv('census.csv')
#df = census_df.where(census_df['SUMLEV']==40)
#df_copy = df.dropna()
#census_df.columns
df_copy = census_df[census_df['SUMLEV'] == 50]
df_copy = df_copy.loc[:,['CTYNAME','POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014','POPESTIMATE2015']]
for ii in df_copy['CTYNAME']:
    print(ii)
#df_copy.head()

Autauga County
Baldwin County
Barbour County
Bibb County
Blount County
Bullock County
Butler County
Calhoun County
Chambers County
Cherokee County
Chilton County
Choctaw County
Clarke County
Clay County
Cleburne County
Coffee County
Colbert County
Conecuh County
Coosa County
Covington County
Crenshaw County
Cullman County
Dale County
Dallas County
DeKalb County
Elmore County
Escambia County
Etowah County
Fayette County
Franklin County
Geneva County
Greene County
Hale County
Henry County
Houston County
Jackson County
Jefferson County
Lamar County
Lauderdale County
Lawrence County
Lee County
Limestone County
Lowndes County
Macon County
Madison County
Marengo County
Marion County
Marshall County
Mobile County
Monroe County
Montgomery County
Morgan County
Perry County
Pickens County
Pike County
Randolph County
Russell County
St. Clair County
Shelby County
Sumter County
Talladega County
Tallapoosa County
Tuscaloosa County
Walker County
Washington County
Wilcox County
Winston County
Aleutians East Borough
Aleutians West Census Area
Anchorage Municipality
Bethel Census Area
Bristol Bay Borough
Denali Borough
Dillingham Census Area
Fairbanks North Star Borough
Haines Borough
Hoonah-Angoon Census Area
Juneau City and Borough
Kenai Peninsula Borough
Ketchikan Gateway Borough
Kodiak Island Borough
Kusilvak Census Area
Lake and Peninsula Borough
Matanuska-Susitna Borough
Nome Census Area
North Slope Borough
Northwest Arctic Borough
Petersburg Borough
Prince of Wales-Hyder Census Area
Sitka City and Borough
Skagway Municipality
Southeast Fairbanks Census Area
Valdez-Cordova Census Area
Wrangell City and Borough
Yakutat City and Borough
Yukon-Koyukuk Census Area
Apache County
Cochise County
Coconino County
Gila County
Graham County
Greenlee County
La Paz County
Maricopa County
Mohave County
Navajo County
Pima County
Pinal County
Santa Cruz County
Yavapai County
Yuma County
Arkansas County
Ashley County
Baxter County
Benton County
Boone County
Bradley County
Calhoun County
Carroll County
Chicot County
Clark County
Clay County
Cleburne County
Cleveland County
Columbia County
Conway County
Craighead County
Crawford County
Crittenden County
Cross County
Dallas County
Desha County
Drew County
Faulkner County
Franklin County
Fulton County
Garland County
Grant County
Greene County
Hempstead County
Hot Spring County
Howard County
Independence County
Izard County
Jackson County
Jefferson County
Johnson County
Lafayette County
Lawrence County
Lee County
Lincoln County
Little River County
Logan County
Lonoke County
Madison County
Marion County
Miller County
Mississippi County
Monroe County
Montgomery County
Nevada County
Newton County
Ouachita County
Perry County
Phillips County
Pike County
Poinsett County
Polk County
Pope County
Prairie County
Pulaski County
Randolph County
St. Francis County
Saline County
Scott County
Searcy County
Sebastian County
Sevier County
Sharp County
Stone County
Union County
Van Buren County
Washington County
White County
Woodruff County
Yell County
Alameda County
Alpine County
Amador County
Butte County
Calaveras County
Colusa County
Contra Costa County
Del Norte County
El Dorado County
Fresno County
Glenn County
Humboldt County
Imperial County
Inyo County
Kern County
Kings County
Lake County
Lassen County
Los Angeles County
Madera County
Marin County
Mariposa County
Mendocino County
Merced County
Modoc County
Mono County
Monterey County
Napa County
Nevada County
Orange County
Placer County
Plumas County
Riverside County
Sacramento County
San Benito County
San Bernardino County
San Diego County
San Francisco County
San Joaquin County
San Luis Obispo County
San Mateo County
Santa Barbara County
Santa Clara County
Santa Cruz County
Shasta County
Sierra County
Siskiyou County
Solano County
Sonoma County
Stanislaus County
Sutter County
Tehama County
Trinity County
Tulare County
Tuolumne County
Ventura County
Yolo County
Yuba County
Adams County
Alamosa County
Arapahoe County
Archuleta County
Baca County
Bent County
Boulder County
Broomfield County
Chaffee County
Cheyenne County
Clear Creek County
Conejos County
Costilla County
Crowley County
Custer County
Delta County
Denver County
Dolores County
Douglas County
Eagle County
Elbert County
El Paso County
Fremont County
Garfield County
Gilpin County
Grand County
Gunnison County
Hinsdale County
Huerfano County
Jackson County
Jefferson County
Kiowa County
Kit Carson County
Lake County
La Plata County
Larimer County
Las Animas County
Lincoln County
Logan County
Mesa County
Mineral County
Moffat County
Montezuma County
Montrose County
Morgan County
Otero County
Ouray County
Park County
Phillips County
Pitkin County
Prowers County
Pueblo County
Rio Blanco County
Rio Grande County
Routt County
Saguache County
San Juan County
San Miguel County
Sedgwick County
Summit County
Teller County
Washington County
Weld County
Yuma County
Fairfield County
Hartford County
Litchfield County
Middlesex County
New Haven County
New London County
Tolland County
Windham County
Kent County
New Castle County
Sussex County
District of Columbia
Alachua County
Baker County
Bay County
Bradford County
Brevard County
Broward County
Calhoun County
Charlotte County
Citrus County
Clay County
Collier County
Columbia County
DeSoto County
Dixie County
Duval County
Escambia County
Flagler County
Franklin County
Gadsden County
Gilchrist County
Glades County
Gulf County
Hamilton County
Hardee County
Hendry County
Hernando County
Highlands County
Hillsborough County
Holmes County
Indian River County
Jackson County
Jefferson County
Lafayette County
Lake County
Lee County
Leon County
Levy County
Liberty County
Madison County
Manatee County
Marion County
Martin County
Miami-Dade County
Monroe County
Nassau County
Okaloosa County
Okeechobee County
Orange County
Osceola County
Palm Beach County
Pasco County
Pinellas County
Polk County
Putnam County
St. Johns County
St. Lucie County
Santa Rosa County
Sarasota County
Seminole County
Sumter County
Suwannee County
Taylor County
Union County
Volusia County
Wakulla County
Walton County
Washington County
Appling County
Atkinson County
Bacon County
Baker County
Baldwin County
Banks County
Barrow County
Bartow County
Ben Hill County
Berrien County
Bibb County
Bleckley County
Brantley County
Brooks County
Bryan County
Bulloch County
Burke County
Butts County
Calhoun County
Camden County
Candler County
Carroll County
Catoosa County
Charlton County
Chatham County
Chattahoochee County
Chattooga County
Cherokee County
Clarke County
Clay County
Clayton County
Clinch County
Cobb County
Coffee County
Colquitt County
Columbia County
Cook County
Coweta County
Crawford County
Crisp County
Dade County
Dawson County
Decatur County
DeKalb County
Dodge County
Dooly County
Dougherty County
Douglas County
Early County
Echols County
Effingham County
Elbert County
Emanuel County
Evans County
Fannin County
Fayette County
Floyd County
Forsyth County
Franklin County
Fulton County
Gilmer County
Glascock County
Glynn County
Gordon County
Grady County
Greene County
Gwinnett County
Habersham County
Hall County
Hancock County
Haralson County
Harris County
Hart County
Heard County
Henry County
Houston County
Irwin County
Jackson County
Jasper County
Jeff Davis County
Jefferson County
Jenkins County
Johnson County
Jones County
Lamar County
Lanier County
Laurens County
Lee County
Liberty County
Lincoln County
Long County
Lowndes County
Lumpkin County
McDuffie County
McIntosh County
Macon County
Madison County
Marion County
Meriwether County
Miller County
Mitchell County
Monroe County
Montgomery County
Morgan County
Murray County
Muscogee County
Newton County
Oconee County
Oglethorpe County
Paulding County
Peach County
Pickens County
Pierce County
Pike County
Polk County
Pulaski County
Putnam County
Quitman County
Rabun County
Randolph County
Richmond County
Rockdale County
Schley County
Screven County
Seminole County
Spalding County
Stephens County
Stewart County
Sumter County
Talbot County
Taliaferro County
Tattnall County
Taylor County
Telfair County
Terrell County
Thomas County
Tift County
Toombs County
Towns County
Treutlen County
Troup County
Turner County
Twiggs County
Union County
Upson County
Walker County
Walton County
Ware County
Warren County
Washington County
Wayne County
Webster County
Wheeler County
White County
Whitfield County
Wilcox County
Wilkes County
Wilkinson County
Worth County
Hawaii County
Honolulu County
Kalawao County
Kauai County
Maui County
Ada County
Adams County
Bannock County
Bear Lake County
Benewah County
Bingham County
Blaine County
Boise County
Bonner County
Bonneville County
Boundary County
Butte County
Camas County
Canyon County
Caribou County
Cassia County
Clark County
Clearwater County
Custer County
Elmore County
Franklin County
Fremont County
Gem County
Gooding County
Idaho County
Jefferson County
Jerome County
Kootenai County
Latah County
Lemhi County
Lewis County
Lincoln County
Madison County
Minidoka County
Nez Perce County
Oneida County
Owyhee County
Payette County
Power County
Shoshone County
Teton County
Twin Falls County
Valley County
Washington County
Adams County
Alexander County
Bond County
Boone County
Brown County
Bureau County
Calhoun County
Carroll County
Cass County
Champaign County
Christian County
Clark County
Clay County
Clinton County
Coles County
Cook County
Crawford County
Cumberland County
DeKalb County
De Witt County
Douglas County
DuPage County
Edgar County
Edwards County
Effingham County
Fayette County
Ford County
Franklin County
Fulton County
Gallatin County
Greene County
Grundy County
Hamilton County
Hancock County
Hardin County
Henderson County
Henry County
Iroquois County
Jackson County
Jasper County
Jefferson County
Jersey County
Jo Daviess County
Johnson County
Kane County
Kankakee County
Kendall County
Knox County
Lake County
LaSalle County
Lawrence County
Lee County
Livingston County
Logan County
McDonough County
McHenry County
McLean County
Macon County
Macoupin County
Madison County
Marion County
Marshall County
Mason County
Massac County
Menard County
Mercer County
Monroe County
Montgomery County
Morgan County
Moultrie County
Ogle County
Peoria County
Perry County
Piatt County
Pike County
Pope County
Pulaski County
Putnam County
Randolph County
Richland County
Rock Island County
St. Clair County
Saline County
Sangamon County
Schuyler County
Scott County
Shelby County
Stark County
Stephenson County
Tazewell County
Union County
Vermilion County
Wabash County
Warren County
Washington County
Wayne County
White County
Whiteside County
Will County
Williamson County
Winnebago County
Woodford County
Adams County
Allen County
Bartholomew County
Benton County
Blackford County
Boone County
Brown County
Carroll County
Cass County
Clark County
Clay County
Clinton County
Crawford County
Daviess County
Dearborn County
Decatur County
DeKalb County
Delaware County
Dubois County
Elkhart County
Fayette County
Floyd County
Fountain County
Franklin County
Fulton County
Gibson County
Grant County
Greene County
Hamilton County
Hancock County
Harrison County
Hendricks County
Henry County
Howard County
Huntington County
Jackson County
Jasper County
Jay County
Jefferson County
Jennings County
Johnson County
Knox County
Kosciusko County
LaGrange County
Lake County
LaPorte County
Lawrence County
Madison County
Marion County
Marshall County
Martin County
Miami County
Monroe County
Montgomery County
Morgan County
Newton County
Noble County
Ohio County
Orange County
Owen County
Parke County
Perry County
Pike County
Porter County
Posey County
Pulaski County
Putnam County
Randolph County
Ripley County
Rush County
St. Joseph County
Scott County
Shelby County
Spencer County
Starke County
Steuben County
Sullivan County
Switzerland County
Tippecanoe County
Tipton County
Union County
Vanderburgh County
Vermillion County
Vigo County
Wabash County
Warren County
Warrick County
Washington County
Wayne County
Wells County
White County
Whitley County
Adair County
Adams County
Allamakee County
Appanoose County
Audubon County
Benton County
Black Hawk County
Boone County
Bremer County
Buchanan County
Buena Vista County
Butler County
Calhoun County
Carroll County
Cass County
Cedar County
Cerro Gordo County
Cherokee County
Chickasaw County
Clarke County
Clay County
Clayton County
Clinton County
Crawford County
Dallas County
Davis County
Decatur County
Delaware County
Des Moines County
Dickinson County
Dubuque County
Emmet County
Fayette County
Floyd County
Franklin County
Fremont County
Greene County
Grundy County
Guthrie County
Hamilton County
Hancock County
Hardin County
Harrison County
Henry County
Howard County
Humboldt County
Ida County
Iowa County
Jackson County
Jasper County
Jefferson County
Johnson County
Jones County
Keokuk County
Kossuth County
Lee County
Linn County
Louisa County
Lucas County
Lyon County
Madison County
Mahaska County
Marion County
Marshall County
Mills County
Mitchell County
Monona County
Monroe County
Montgomery County
Muscatine County
O'Brien County
Osceola County
Page County
Palo Alto County
Plymouth County
Pocahontas County
Polk County
Pottawattamie County
Poweshiek County
Ringgold County
Sac County
Scott County
Shelby County
Sioux County
Story County
Tama County
Taylor County
Union County
Van Buren County
Wapello County
Warren County
Washington County
Wayne County
Webster County
Winnebago County
Winneshiek County
Woodbury County
Worth County
Wright County
Allen County
Anderson County
Atchison County
Barber County
Barton County
Bourbon County
Brown County
Butler County
Chase County
Chautauqua County
Cherokee County
Cheyenne County
Clark County
Clay County
Cloud County
Coffey County
Comanche County
Cowley County
Crawford County
Decatur County
Dickinson County
Doniphan County
Douglas County
Edwards County
Elk County
Ellis County
Ellsworth County
Finney County
Ford County
Franklin County
Geary County
Gove County
Graham County
Grant County
Gray County
Greeley County
Greenwood County
Hamilton County
Harper County
Harvey County
Haskell County
Hodgeman County
Jackson County
Jefferson County
Jewell County
Johnson County
Kearny County
Kingman County
Kiowa County
Labette County
Lane County
Leavenworth County
Lincoln County
Linn County
Logan County
Lyon County
McPherson County
Marion County
Marshall County
Meade County
Miami County
Mitchell County
Montgomery County
Morris County
Morton County
Nemaha County
Neosho County
Ness County
Norton County
Osage County
Osborne County
Ottawa County
Pawnee County
Phillips County
Pottawatomie County
Pratt County
Rawlins County
Reno County
Republic County
Rice County
Riley County
Rooks County
Rush County
Russell County
Saline County
Scott County
Sedgwick County
Seward County
Shawnee County
Sheridan County
Sherman County
Smith County
Stafford County
Stanton County
Stevens County
Sumner County
Thomas County
Trego County
Wabaunsee County
Wallace County
Washington County
Wichita County
Wilson County
Woodson County
Wyandotte County
Adair County
Allen County
Anderson County
Ballard County
Barren County
Bath County
Bell County
Boone County
Bourbon County
Boyd County
Boyle County
Bracken County
Breathitt County
Breckinridge County
Bullitt County
Butler County
Caldwell County
Calloway County
Campbell County
Carlisle County
Carroll County
Carter County
Casey County
Christian County
Clark County
Clay County
Clinton County
Crittenden County
Cumberland County
Daviess County
Edmonson County
Elliott County
Estill County
Fayette County
Fleming County
Floyd County
Franklin County
Fulton County
Gallatin County
Garrard County
Grant County
Graves County
Grayson County
Green County
Greenup County
Hancock County
Hardin County
Harlan County
Harrison County
Hart County
Henderson County
Henry County
Hickman County
Hopkins County
Jackson County
Jefferson County
Jessamine County
Johnson County
Kenton County
Knott County
Knox County
Larue County
Laurel County
Lawrence County
Lee County
Leslie County
Letcher County
Lewis County
Lincoln County
Livingston County
Logan County
Lyon County
McCracken County
McCreary County
McLean County
Madison County
Magoffin County
Marion County
Marshall County
Martin County
Mason County
Meade County
Menifee County
Mercer County
Metcalfe County
Monroe County
Montgomery County
Morgan County
Muhlenberg County
Nelson County
Nicholas County
Ohio County
Oldham County
Owen County
Owsley County
Pendleton County
Perry County
Pike County
Powell County
Pulaski County
Robertson County
Rockcastle County
Rowan County
Russell County
Scott County
Shelby County
Simpson County
Spencer County
Taylor County
Todd County
Trigg County
Trimble County
Union County
Warren County
Washington County
Wayne County
Webster County
Whitley County
Wolfe County
Woodford County
Acadia Parish
Allen Parish
Ascension Parish
Assumption Parish
Avoyelles Parish
Beauregard Parish
Bienville Parish
Bossier Parish
Caddo Parish
Calcasieu Parish
Caldwell Parish
Cameron Parish
Catahoula Parish
Claiborne Parish
Concordia Parish
De Soto Parish
East Baton Rouge Parish
East Carroll Parish
East Feliciana Parish
Evangeline Parish
Franklin Parish
Grant Parish
Iberia Parish
Iberville Parish
Jackson Parish
Jefferson Parish
Jefferson Davis Parish
Lafayette Parish
Lafourche Parish
LaSalle Parish
Lincoln Parish
Livingston Parish
Madison Parish
Morehouse Parish
Natchitoches Parish
Orleans Parish
Ouachita Parish
Plaquemines Parish
Pointe Coupee Parish
Rapides Parish
Red River Parish
Richland Parish
Sabine Parish
St. Bernard Parish
St. Charles Parish
St. Helena Parish
St. James Parish
St. John the Baptist Parish
St. Landry Parish
St. Martin Parish
St. Mary Parish
St. Tammany Parish
Tangipahoa Parish
Tensas Parish
Terrebonne Parish
Union Parish
Vermilion Parish
Vernon Parish
Washington Parish
Webster Parish
West Baton Rouge Parish
West Carroll Parish
West Feliciana Parish
Winn Parish
Androscoggin County
Aroostook County
Cumberland County
Franklin County
Hancock County
Kennebec County
Knox County
Lincoln County
Oxford County
Penobscot County
Piscataquis County
Sagadahoc County
Somerset County
Waldo County
Washington County
York County
Allegany County
Anne Arundel County
Baltimore County
Calvert County
Caroline County
Carroll County
Cecil County
Charles County
Dorchester County
Frederick County
Garrett County
Harford County
Howard County
Kent County
Montgomery County
Prince George's County
Queen Anne's County
St. Mary's County
Somerset County
Talbot County
Washington County
Wicomico County
Worcester County
Baltimore city
Barnstable County
Berkshire County
Bristol County
Dukes County
Essex County
Franklin County
Hampden County
Hampshire County
Middlesex County
Nantucket County
Norfolk County
Plymouth County
Suffolk County
Worcester County
Alcona County
Alger County
Allegan County
Alpena County
Antrim County
Arenac County
Baraga County
Barry County
Bay County
Benzie County
Berrien County
Branch County
Calhoun County
Cass County
Charlevoix County
Cheboygan County
Chippewa County
Clare County
Clinton County
Crawford County
Delta County
Dickinson County
Eaton County
Emmet County
Genesee County
Gladwin County
Gogebic County
Grand Traverse County
Gratiot County
Hillsdale County
Houghton County
Huron County
Ingham County
Ionia County
Iosco County
Iron County
Isabella County
Jackson County
Kalamazoo County
Kalkaska County
Kent County
Keweenaw County
Lake County
Lapeer County
Leelanau County
Lenawee County
Livingston County
Luce County
Mackinac County
Macomb County
Manistee County
Marquette County
Mason County
Mecosta County
Menominee County
Midland County
Missaukee County
Monroe County
Montcalm County
Montmorency County
Muskegon County
Newaygo County
Oakland County
Oceana County
Ogemaw County
Ontonagon County
Osceola County
Oscoda County
Otsego County
Ottawa County
Presque Isle County
Roscommon County
Saginaw County
St. Clair County
St. Joseph County
Sanilac County
Schoolcraft County
Shiawassee County
Tuscola County
Van Buren County
Washtenaw County
Wayne County
Wexford County
Aitkin County
Anoka County
Becker County
Beltrami County
Benton County
Big Stone County
Blue Earth County

Beaufort County
Bertie County
Bladen County
Brunswick County
Buncombe County
Burke County
Cabarrus County
Caldwell County
Camden County
Carteret County
Caswell County
Catawba County
Chatham County
Cherokee County
Chowan County
Clay County
Cleveland County
Columbus County
Craven County
Cumberland County
Currituck County
Dare County
Davidson County
Davie County
Duplin County
Durham County
Edgecombe County
Forsyth County
Franklin County
Gaston County
Gates County
Graham County
Granville County
Greene County
Guilford County
Halifax County
Harnett County
Haywood County
Henderson County
Hertford County
Hoke County
Hyde County
Iredell County
Jackson County
Johnston County
Jones County
Lee County
Lenoir County
Lincoln County
McDowell County
Macon County
Madison County
Martin County
Mecklenburg County
Mitchell County
Montgomery County
Moore County
Nash County
New Hanover County
Northampton County
Onslow County
Orange County
Pamlico County
Pasquotank County
Pender County
Perquimans County
Person County
Pitt County
Polk County
Randolph County
Richmond County
Robeson County
Rockingham County
Rowan County
Rutherford County
Sampson County
Scotland County
Stanly County
Stokes County
Surry County
Swain County
Transylvania County
Tyrrell County
Union County
Vance County
Wake County
Warren County
Washington County
Watauga County
Wayne County
Wilkes County
Wilson County
Yadkin County
Yancey County
Adams County
Barnes County
Benson County
Billings County
Bottineau County
Bowman County
Burke County
Burleigh County
Cass County
Cavalier County
Dickey County
Divide County
Dunn County
Eddy County
Emmons County
Foster County
Golden Valley County
Grand Forks County
Grant County
Griggs County
Hettinger County
Kidder County
LaMoure County
Logan County
McHenry County
McIntosh County
McKenzie County
McLean County
Mercer County
Morton County
Mountrail County
Nelson County
Oliver County
Pembina County
Pierce County
Ramsey County
Ransom County
Renville County
Richland County
Rolette County
Sargent County
Sheridan County
Sioux County
Slope County
Stark County
Steele County
Stutsman County
Towner County
Traill County
Walsh County
Ward County
Wells County
Williams County
Adams County
Allen County
Ashland County
Ashtabula County
Athens County
Auglaize County
Belmont County
Brown County
Butler County
Carroll County
Champaign County
Clark County
Clermont County
Clinton County
Columbiana County
Coshocton County
Crawford County
Cuyahoga County
Darke County
Defiance County
Delaware County
Erie County
Fairfield County
Fayette County
Franklin County
Fulton County
Gallia County
Geauga County
Greene County
Guernsey County
Hamilton County
Hancock County
Hardin County
Harrison County
Henry County
Highland County
Hocking County
Holmes County
Huron County
Jackson County
Jefferson County
Knox County
Lake County
Lawrence County
Licking County
Logan County
Lorain County
Lucas County
Madison County
Mahoning County
Marion County
Medina County
Meigs County
Mercer County
Miami County
Monroe County
Montgomery County
Morgan County
Morrow County
Muskingum County
Noble County
Ottawa County
Paulding County
Perry County
Pickaway County
Pike County
Portage County
Preble County
Putnam County
Richland County
Ross County
Sandusky County
Scioto County
Seneca County
Shelby County
Stark County
Summit County
Trumbull County
Tuscarawas County
Union County
Van Wert County
Vinton County
Warren County
Washington County
Wayne County
Williams County
Wood County
Wyandot County
Adair County
Alfalfa County
Atoka County
Beaver County
Beckham County
Blaine County
Bryan County
Caddo County
Canadian County
Carter County
Cherokee County
Choctaw County
Cimarron County
Cleveland County
Coal County
Comanche County
Cotton County
Craig County
Creek County
Custer County
Delaware County
Dewey County
Ellis County
Garfield County
Garvin County
Grady County
Grant County
Greer County
Harmon County
Harper County
Haskell County
Hughes County
Jackson County
Jefferson County
Johnston County
Kay County
Kingfisher County
Kiowa County
Latimer County
Le Flore County
Lincoln County
Logan County
Love County
McClain County
McCurtain County
McIntosh County
Major County
Marshall County
Mayes County
Murray County
Muskogee County
Noble County
Nowata County
Okfuskee County
Oklahoma County
Okmulgee County
Osage County
Ottawa County
Pawnee County
Payne County
Pittsburg County
Pontotoc County
Pottawatomie County
Pushmataha County
Roger Mills County
Rogers County
Seminole County
Sequoyah County
Stephens County
Texas County
Tillman County
Tulsa County
Wagoner County
Washington County
Washita County
Woods County
Woodward County
Baker County
Benton County
Clackamas County
Clatsop County
Columbia County
Coos County
Crook County
Curry County
Deschutes County
Douglas County
Gilliam County
Grant County
Harney County
Hood River County
Jackson County
Jefferson County
Josephine County
Klamath County
Lake County
Lane County
Lincoln County
Linn County
Malheur County
Marion County
Morrow County
Multnomah County
Polk County
Sherman County
Tillamook County
Umatilla County
Union County
Wallowa County
Wasco County
Washington County
Wheeler County
Yamhill County
Adams County
Allegheny County
Armstrong County
Beaver County
Bedford County
Berks County
Blair County
Bradford County
Bucks County
Butler County
Cambria County
Cameron County
Carbon County
Centre County
Chester County
Clarion County
Clearfield County
Clinton County
Columbia County
Crawford County
Cumberland County
Dauphin County
Delaware County
Elk County
Erie County
Fayette County
Forest County
Franklin County
Fulton County
Greene County
Huntingdon County
Indiana County
Jefferson County
Juniata County
Lackawanna County
Lancaster County
Lawrence County
Lebanon County
Lehigh County
Luzerne County
Lycoming County
McKean County
Mercer County
Mifflin County
Monroe County
Montgomery County
Montour County
Northampton County
Northumberland County
Perry County
Philadelphia County
Pike County
Potter County
Schuylkill County
Snyder County
Somerset County
Sullivan County
Susquehanna County
Tioga County
Union County
Venango County
Warren County
Washington County
Wayne County
Westmoreland County
Wyoming County
York County
Bristol County
Kent County
Newport County
Providence County
Washington County
Abbeville County
Aiken County
Allendale County
Anderson County
Bamberg County
Barnwell County
Beaufort County
Berkeley County
Calhoun County
Charleston County
Cherokee County
Chester County
Chesterfield County
Clarendon County
Colleton County
Darlington County
Dillon County
Dorchester County
Edgefield County
Fairfield County
Florence County
Georgetown County
Greenville County
Greenwood County
Hampton County
Horry County
Jasper County
Kershaw County
Lancaster County
Laurens County
Lee County
Lexington County
McCormick County
Marion County
Marlboro County
Newberry County
Oconee County
Orangeburg County
Pickens County
Richland County
Saluda County
Spartanburg County
Sumter County
Union County
Williamsburg County
York County
Aurora County
Beadle County
Bennett County
Bon Homme County
Brookings County
Brown County
Brule County
Buffalo County
Butte County
Campbell County
Charles Mix County
Clark County
Clay County
Codington County
Corson County
Custer County
Davison County
Day County
Deuel County
Dewey County
Douglas County
Edmunds County
Fall River County
Faulk County
Grant County
Gregory County
Haakon County
Hamlin County
Hand County
Hanson County
Harding County
Hughes County
Hutchinson County
Hyde County
Jackson County
Jerauld County
Jones County
Kingsbury County
Lake County
Lawrence County
Lincoln County
Lyman County
McCook County
McPherson County
Marshall County
Meade County
Mellette County
Miner County
Minnehaha County
Moody County
Oglala Lakota County
Pennington County
Perkins County
Potter County
Roberts County
Sanborn County
Spink County
Stanley County
Sully County
Todd County
Tripp County
Turner County
Union County
Walworth County
Yankton County
Ziebach County
Anderson County
Bedford County
Benton County
Bledsoe County
Blount County
Bradley County
Campbell County
Cannon County
Carroll County
Carter County
Cheatham County
Chester County
Claiborne County
Clay County
Cocke County
Coffee County
Crockett County
Cumberland County
Davidson County
Decatur County
DeKalb County
Dickson County
Dyer County
Fayette County
Fentress County
Franklin County
Gibson County
Giles County
Grainger County
Greene County
Grundy County
Hamblen County
Hamilton County
Hancock County
Hardeman County
Hardin County
Hawkins County
Haywood County
Henderson County
Henry County
Hickman County
Houston County
Humphreys County
Jackson County
Jefferson County
Johnson County
Knox County
Lake County
Lauderdale County
Lawrence County
Lewis County
Lincoln County
Loudon County
McMinn County
McNairy County
Macon County
Madison County
Marion County
Marshall County
Maury County
Meigs County
Monroe County
Montgomery County
Moore County
Morgan County
Obion County
Overton County
Perry County
Pickett County
Polk County
Putnam County
Rhea County
Roane County
Robertson County
Rutherford County
Scott County
Sequatchie County
Sevier County
Shelby County
Smith County
Stewart County
Sullivan County
Sumner County
Tipton County
Trousdale County
Unicoi County
Union County
Van Buren County
Warren County
Washington County
Wayne County
Weakley County
White County
Williamson County
Wilson County
Anderson County
Andrews County
Angelina County
Aransas County
Archer County
Armstrong County
Atascosa County
Austin County
Bailey County
Bandera County
Bastrop County
Baylor County
Bee County
Bell County
Bexar County
Blanco County
Borden County
Bosque County
Bowie County
Brazoria County
Brazos County
Brewster County
Briscoe County
Brooks County
Brown County
Burleson County
Burnet County
Caldwell County
Calhoun County
Callahan County
Cameron County
Camp County
Carson County
Cass County
Castro County
Chambers County
Cherokee County
Childress County
Clay County
Cochran County
Coke County
Coleman County
Collin County
Collingsworth County
Colorado County
Comal County
Comanche County
Concho County
Cooke County
Coryell County
Cottle County
Crane County
Crockett County
Crosby County
Culberson County
Dallam County
Dallas County
Dawson County
Deaf Smith County
Delta County
Denton County
DeWitt County
Dickens County
Dimmit County
Donley County
Duval County
Eastland County
Ector County
Edwards County
Ellis County
El Paso County
Erath County
Falls County
Fannin County
Fayette County
Fisher County
Floyd County
Foard County
Fort Bend County
Franklin County
Freestone County
Frio County
Gaines County
Galveston County
Garza County
Gillespie County
Glasscock County
Goliad County
Gonzales County
Gray County
Grayson County
Gregg County
Grimes County
Guadalupe County
Hale County
Hall County
Hamilton County
Hansford County
Hardeman County
Hardin County
Harris County
Harrison County
Hartley County
Haskell County
Hays County
Hemphill County
Henderson County
Hidalgo County
Hill County
Hockley County
Hood County
Hopkins County
Houston County
Howard County
Hudspeth County
Hunt County
Hutchinson County
Irion County
Jack County
Jackson County
Jasper County
Jeff Davis County
Jefferson County
Jim Hogg County
Jim Wells County
Johnson County
Jones County
Karnes County
Kaufman County
Kendall County
Kenedy County
Kent County
Kerr County
Kimble County
King County
Kinney County
Kleberg County
Knox County
Lamar County
Lamb County
Lampasas County
La Salle County
Lavaca County
Lee County
Leon County
Liberty County
Limestone County
Lipscomb County
Live Oak County
Llano County
Loving County
Lubbock County
Lynn County
McCulloch County
McLennan County
McMullen County
Madison County
Marion County
Martin County
Mason County
Matagorda County
Maverick County
Medina County
Menard County
Midland County
Milam County
Mills County
Mitchell County
Montague County
Montgomery County
Moore County
Morris County
Motley County
Nacogdoches County
Navarro County
Newton County
Nolan County
Nueces County
Ochiltree County
Oldham County
Orange County
Palo Pinto County
Panola County
Parker County
Parmer County
Pecos County
Polk County
Potter County
Presidio County
Rains County
Randall County
Reagan County
Real County
Red River County
Reeves County
Refugio County
Roberts County
Robertson County
Rockwall County
Runnels County
Rusk County
Sabine County
San Augustine County
San Jacinto County
San Patricio County
San Saba County
Schleicher County
Scurry County
Shackelford County
Shelby County
Sherman County
Smith County
Somervell County
Starr County
Stephens County
Sterling County
Stonewall County
Sutton County
Swisher County
Tarrant County
Taylor County
Terrell County
Terry County
Throckmorton County
Titus County
Tom Green County
Travis County
Trinity County
Tyler County
Upshur County
Upton County
Uvalde County
Val Verde County
Van Zandt County
Victoria County
Walker County
Waller County
Ward County
Washington County
Webb County
Wharton County
Wheeler County
Wichita County
Wilbarger County
Willacy County
Williamson County
Wilson County
Winkler County
Wise County
Wood County
Yoakum County
Young County
Zapata County
Zavala County
Beaver County
Box Elder County
Cache County
Carbon County
Daggett County
Davis County
Duchesne County
Emery County
Garfield County
Grand County
Iron County
Juab County
Kane County
Millard County
Morgan County
Piute County
Rich County
Salt Lake County
San Juan County
Sanpete County
Sevier County
Summit County
Tooele County
Uintah County
Utah County
Wasatch County
Washington County
Wayne County
Weber County
Addison County
Bennington County
Caledonia County
Chittenden County
Essex County
Franklin County
Grand Isle County
Lamoille County
Orange County
Orleans County
Rutland County
Washington County
Windham County
Windsor County
Accomack County
Albemarle County
Alleghany County
Amelia County
Amherst County
Appomattox County
Arlington County
Augusta County
Bath County
Bedford County
Bland County
Botetourt County
Brunswick County
Buchanan County
Buckingham County
Campbell County
Caroline County
Carroll County
Charles City County
Charlotte County
Chesterfield County
Clarke County
Craig County
Culpeper County
Cumberland County
Dickenson County
Dinwiddie County
Essex County
Fairfax County
Fauquier County
Floyd County
Fluvanna County
Franklin County
Frederick County
Giles County
Gloucester County
Goochland County
Grayson County
Greene County
Greensville County
Halifax County
Hanover County
Henrico County
Henry County
Highland County
Isle of Wight County
James City County
King and Queen County
King George County
King William County
Lancaster County
Lee County
Loudoun County
Louisa County
Lunenburg County
Madison County
Mathews County
Mecklenburg County
Middlesex County
Montgomery County
Nelson County
New Kent County
Northampton County
Northumberland County
Nottoway County
Orange County
Page County
Patrick County
Pittsylvania County
Powhatan County
Prince Edward County
Prince George County
Prince William County
Pulaski County
Rappahannock County
Richmond County
Roanoke County
Rockbridge County
Rockingham County
Russell County
Scott County
Shenandoah County
Smyth County
Southampton County
Spotsylvania County
Stafford County
Surry County
Sussex County
Tazewell County
Warren County
Washington County
Westmoreland County
Wise County
Wythe County
York County
Alexandria city
Bristol city
Buena Vista city
Charlottesville city
Chesapeake city
Colonial Heights city
Covington city
Danville city
Emporia city
Fairfax city
Falls Church city
Franklin city
Fredericksburg city
Galax city
Hampton city
Harrisonburg city
Hopewell city
Lexington city
Lynchburg city
Manassas city
Manassas Park city
Martinsville city
Newport News city
Norfolk city
Norton city
Petersburg city
Poquoson city
Portsmouth city
Radford city
Richmond city
Roanoke city
Salem city
Staunton city
Suffolk city
Virginia Beach city
Waynesboro city
Williamsburg city
Winchester city
Adams County
Asotin County
Benton County
Chelan County
Clallam County
Clark County
Columbia County
Cowlitz County
Douglas County
Ferry County
Franklin County
Garfield County
Grant County
Grays Harbor County
Island County
Jefferson County
King County
Kitsap County
Kittitas County
Klickitat County
Lewis County
Lincoln County
Mason County
Okanogan County
Pacific County
Pend Oreille County
Pierce County
San Juan County
Skagit County
Skamania County
Snohomish County
Spokane County
Stevens County
Thurston County
Wahkiakum County
Walla Walla County
Whatcom County
Whitman County
Yakima County
Barbour County
Berkeley County
Boone County
Braxton County
Brooke County
Cabell County
Calhoun County
Clay County
Doddridge County
Fayette County
Gilmer County
Grant County
Greenbrier County
Hampshire County
Hancock County
Hardy County
Harrison County
Jackson County
Jefferson County
Kanawha County
Lewis County
Lincoln County
Logan County
McDowell County
Marion County
Marshall County
Mason County
Mercer County
Mineral County
Mingo County
Monongalia County
Monroe County
Morgan County
Nicholas County
Ohio County
Pendleton County
Pleasants County
Pocahontas County
Preston County
Putnam County
Raleigh County
Randolph County
Ritchie County
Roane County
Summers County
Taylor County
Tucker County
Tyler County
Upshur County
Wayne County
Webster County
Wetzel County
Wirt County
Wood County
Wyoming County
Adams County
Ashland County
Barron County
Bayfield County
Brown County
Buffalo County
Burnett County
Calumet County
Chippewa County
Clark County
Columbia County
Crawford County
Dane County
Dodge County
Door County
Douglas County
Dunn County
Eau Claire County
Florence County
Fond du Lac County
Forest County
Grant County
Green County
Green Lake County
Iowa County
Iron County
Jackson County
Jefferson County
Juneau County
Kenosha County
Kewaunee County
La Crosse County
Lafayette County
Langlade County
Lincoln County
Manitowoc County
Marathon County
Marinette County
Marquette County
Menominee County
Milwaukee County
Monroe County
Oconto County
Oneida County
Outagamie County
Ozaukee County
Pepin County
Pierce County
Polk County
Portage County
Price County
Racine County
Richland County
Rock County
Rusk County
St. Croix County
Sauk County
Sawyer County
Shawano County
Sheboygan County
Taylor County
Trempealeau County
Vernon County
Vilas County
Walworth County
Washburn County
Washington County
Waukesha County
Waupaca County
Waushara County
Winnebago County
Wood County
Albany County
Big Horn County
Campbell County
Carbon County
Converse County
Crook County
Fremont County
Goshen County
Hot Springs County
Johnson County
Laramie County
Lincoln County
Natrona County
Niobrara County
Park County
Platte County
Sheridan County
Sublette County
Sweetwater County
Teton County
Uinta County
Washakie County
Weston County